const express = require("express");
const bodyParser = require("body-parser");
const db = require("./module/db2");
const jwt = require("./module/jwt");
const path = require("path");
const app = express();
app.use(bodyParser.json());
app.use(express.static(path.resolve(__dirname,"../src/assets/")));
app.all("*",function (req,res,next) {
    res.header("Access-Control-Allow-Origin","*");
    res.header("Access-Control-Allow-Headers","content-type,authorization");
    res.header("Access-Control-Allow-Methods","DELETE,PUT,GET,POST,OPTIONS");
    next();
})

//tl 登录
app.post("/login",function (req,res) {
    console.log(req.body.adminName,req.body.passWord)
    if(req.body.adminName/1 === 18234115020 && req.body.passWord/1 ===666666){
        res.json({
            ok:1,
            msg:"登录成功",
            userId:1,
            userName:18234115020
        })
    }else{
        res.json({
            data:{
                ok:-1,
                msg:"登录失败"
            }
        })
    }
});
app.get("/animal",function(req,res){
    res.json({
        data:{
            pageSum:1,
            pageIndex:1,
            pet:[{
                typeId:1,
                typeName:"哈士奇",
                price:2980,
                icon:"/hello/petmarket/img/20180820nsmqmz.jpg",
            },{
                typeId:2,
                typeName:"哈士奇",
                price:2980,
                icon:"/hello/petmarket/img/20180820nsmqmz.jpg",
            },{
                typeId:3,
                typeName:"哈士奇",
                price:2980,
                icon:"/hello/petmarket/img/20180820nsmqmz.jpg"
            },{
                typeId:4,
                typeName:"哈士奇",
                price:2980,
                icon:"/hello/petmarket/img/20180820nsmqmz.jpg"
            },{
                typeId:5,
                typeName:"哈士奇",
                price:2980,
                icon:"/hello/petmarket/img/20180820nsmqmz.jpg"
            },{
                typeId:6,
                typeName:"哈士奇",
                price:2980,
                icon:"/hello/petmarket/img/20180820nsmqmz.jpg"
            }]
        }
    })
})
app.get("/xq",function(req,res){
    res.json({
        data:{
            icon:["/hello/petmarket/img/210205623263.jpg","/hello/petmarket/img/210205623263.jpg","/hello/petmarket/img/210205623263.jpg"],
            petIntroduce:"出售纯种健康宠物狗哈士奇支持上门挑选送货上门",
            getPrice:2980,
            petNum:20,
            petAge:"3个月",
            dogOrCat:2,
            boyOrGirl:1
        }
    })
})
app.get("/gwc",function(req,res){
    console.log(111)
    res.json({
        pageSum:1,
        data:
            [{
            icon:"/hello/petmarket/img/20180820nsmqmz.jpg",
            name:"哈士奇1",
            goodsNum:1,
            price:2980,
            pType:0,
            goodsId:1
        },{
            icon:"/hello/petmarket/img/4ce5c49d1451e641adacddcc5cbadfae.jpg",
            name:"鲜虾味大鸡腿",
            price:549,
            goodsNum:1,
            productDescription:"鲜虾味",
            pType:1,
            goodsId:2
            }]
    })
})
app.get("/goods",function(req,res){
    res.json({
        data:[{
            price:[599,549],
            stock:1579,
            pic:"/hello/daily/img/one.jpg",
            goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
            goodsId:1
        },{
            price:[599,549],
            stock:1579,
            pic:"/hello/daily/img/one.jpg",
            goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
            goodsId:1
        },{
            price:[599,549],
            stock:1579,
            pic:"/hello/daily/img/one.jpg",
            goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
            goodsId:1
        },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },{
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            },
            {
                price:[599,549],
                stock:1579,
                pic:"/hello/daily/img/one.jpg",
                goodsName:"麦富迪双拼标准颗粒成犬粮10KG",
                goodsId:1
            }]
    })
})
app.post("/account",function(req,res){
    console.log(req.body.userName,req.body.userId)
    res.json({
        detailedAddress:"北京市昌平区沙河镇沙阳路振宇公寓422",
        detailedName:"刘鑫",
        contactNumber:18234115020,
    })
})
app.listen(8088,function(){
    console.log("成功");
})